server:
  port:
    8888
spring:
  application:
    name:
      gateway-service
  cloud:
    config:
      enabled:
        false
    discovery:
      enabled:
        true
    gateway:
      discovery:
        locator:
          lower-case-service-id:
            true
eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:8000/eureka
  instance:
    prefer-ip-address:
      true
